# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "dev/dev/acr/terraform.tfstate"
    resource_group_name  = "vinayak-terraform"
    storage_account_name = "tfdevbackendvinayak"
  }
}
